/*


Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.


ToDo:

- Fibonacci sequence, condition : values do not exceed four million,
- Find the even values in Fibonacci sequence
- calculate sum of even values
*/

import * as A from "fp-ts/lib/Array";
import { pipe } from "fp-ts/lib/function";

let DataSet = Array.from(Array(1000000), (_, x) => x);
const FibonacciNotExceed4Mil = pipe(
  A.array.map(DataSet, (x) => x),
  A.reduce(0, (prev, next) => (prev + next <= 4000000 ? prev + next : 0)),
);

console.log(FibonacciNotExceed4Mil);
